fix: java.lang.NullPointerException 	com.gammon.qs.service.ResourceSummaryService.addResourceSummary(ResourceSummaryService.java:1176) 	com.gammon.qs.dao.SubcontractWSDao.insertSCPackage(SubcontractWSDao.java:385) 	com.gammon.qs.service.SubcontractService.saveOrUpdateSCPackage(SubcontractService.java:3658) 	com.gammon.pcms.web.controller.AttachmentController.generateSCAttachment(AttachmentController.java:304) 	com.gammon.qs.service.admin.AdminService.obtainCanAccessJobNoStringList(AdminService.java:82)
java.lang.IndexOutOfBoundsException
	com.gammon.qs.dao.JobInfoHBDao.obtainJobInfoByJobNumberList(JobInfoHBDao.java:77)
	com.gammon.qs.service.MainCertService.getCertificateDashboardData(MainCertService.java:795)
	
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
	com.gammon.qs.dao.SubcontractWSDao.updateSCWorkScopeInJDE(SubcontractWSDao.java:625)